{% set name = "turbo-seti" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/turbo_seti-{{ version }}.tar.gz
  sha256: 7690f024e1ab72672cc7cf0909ab6a1c6643e5833ff82b3d5a5111611f2c05ef

build:
  entry_points:
    - turboSETI = turbo_seti.find_doppler.seti_event:main
    - plotSETI = turbo_seti.find_event.run_pipelines:main
    - dat_filter = turbo_seti.find_event.dat_filter:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy
    - blimpy >=2.0.34
    - cloudpickle
    - dask-core
    - fsspec
    - numba
    - numpy
    - pandas
    - python >=3.6
    - toolz

test:
  imports:
    - turbo_seti
  commands:
    - pip check
    - turboSETI --help
    - plotSETI --help
    - dat_filter --help
  requires:
    - pip

about:
  home: https://github.com/UCBerkeleySETI/turbo_seti
  summary: Analysis tool for the search of narrow band drifting signals in filterbank data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
